version: '3.4'
services:
  mongodb:
    image: mongo:7.0.28
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data

  cattle-home:
    build: ./
    ports:
      - '8085:8085'
    links:
      - 'mongodb:mongodb'
    depends_on:
      mongodb:
        condition: service_started
    environment:
      ASPNETCORE_URLS: http://+:8085
      Mongo__DatabaseUri: mongodb://mongodb:27017/
      Mongo__DatabaseName: lis-be4fe-cattle-home
      CattleApi__BaseUrl: http://host.docker.internal:5000
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
