<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Integrations\CattleApi\CattleApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\src\Api\Fixtures\CattleApi\cattle.json"
             Link="Fixtures\CattleApi\cattle.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
