<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.CommonSchema.Serilog"/>
    <PackageReference Include="Elastic.Serilog.Enrichers.Web"/>
    <PackageReference Include="Microsoft.AspNetCore.HeaderPropagation"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="MongoDB.Driver.Authentication.AWS" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Enrichers.ClientInfo"/>
    <PackageReference Include="Serilog.Enrichers.Environment"/>
    <PackageReference Include="Serilog.Extensions.Hosting"/>
    <PackageReference Include="Serilog.Settings.Configuration"/>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>
</Project>
